### ISSUE TITLE
integrá-lo ao front do magento

### ISSUE THREAD

**Issue by marcelowu** [ianitsky/module-viacep#1]
https://github.com/koan-solucoes/magento2-autocompletar-endereco/blob/master/app/code/Koan/Autocomplete/Model/Endereco/Viacep.php

**Comment by ianitsky** [comment]
Olá @marcelowu , não consigo mais abrir esse arquivo. Aparece 404

**Comment by marcelowu** [comment]
https://github.com/Bleez/Bleez-Correios/blob/master/Model/Endereco/Viacep.php

**Comment by marcelowu** [comment]
https://github.com/Bleez/Bleez-Correios/blob/master/Model/Endereco/Viacep.php
